#ifndef HTTP_PARSE_STATE_H
#define HTTP_PARSE_STATE_H

typedef enum HttpParseState HttpParseState;
enum HttpParseState
{
	NOT_STARTED=0,
	IN_METHOD=1,
	METHOD_COMPLETE=2,
	IN_PATH=3,
	IN_PARAM_KEY=4,
	IN_PARAM_VALUE=5,
	PATH_PARAMS_COMPLETE=6,
	IN_VERSION=7,
	VERSION_COMPLETE=8,
	HEADER_START=9,
	IN_HEADER_KEY=10,
	HEADER_KEY_COMPLETE=11,
	IN_HEADER_VALUE=12,
	HEADER_VALUE_COMPLETE=13,
	HEADERS_COMPLETE=14,
	IN_BODY=15,
	BODY_COMPLETE=16,
	IN_STATUS=17,
	STATUS_COMPLETE=18,
	IN_STATUS_STRING=19,
	STATUS_STRING_COMPLETE=20,
	PARSED_SUCCESSFULLY=21
};

#endif