#ifndef TYPE_SUPPORT_H
#define TYPE_SUPPORT_H

typedef enum Type_Support Type_Support;
enum Type_Support
{
	 STRING_JSON = 0
	,NUMBER_JSON = 1
	,NULL_JSON = 2
	,TRUE_JSON = 3
	,FALSE_JSON = 4
	,ARRAY_JSON = 5
	,OBJECT_JSON = 6
	,INTEGER_JSON = 7
	,DOUBLE_JSON = 8
	,BOOLEAN_JSON = 9
	,NODE_JSON = 10
	/*,CLASSNAME_JSON*/
	,MYOBJECT_JSON
	,MYOBJECTSUB_JSON
};

#endif